#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "Installing development dependencies..."

sudo uv pip install wheel --upgrade --system
sudo uv pip install -r requirements-dev.txt --system

curl -fsSL https://mongoose-os.com/downloads/mos/install.sh | /bin/bash
sudo ln -s ~/.mos/bin/mos /usr/bin/mos

pre-commit install
