#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "Installing development dependencies..."

sudo uv pip install wheel --upgrade --system
sudo uv pip install --system --group dev -e .

curl -fsSL https://mongoose-os.com/downloads/mos/install.sh | /bin/bash
sudo ln -s ~/.mos/bin/mos /usr/bin/mos

pre-commit install

cargo install --locked --bin jj jj-cli
